### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by hwhesselink**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Python3 dropped iteritems, this PR changes them to items.  The only downside to items is that, because it's not a generator, it doesn't handle large dataset well.  Given that the changes are for the interfaces and zones files I don't believe that will be an issue.

BTW, the Travis CI check is failing on Wheezy because Debian no longer supports it so the build env. download isn't found.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by vutny — COMMENTED** [review]
I guess the test suite for Debian Wheezy should be dropped, since the distro is EOL for a long time for now.

And, Jinja filter `dictsort()` is more portable way of iterating over dictionaries than calling Py2 or 3 methods directly. Like this:
```
zone_data.get('interfaces', {})|dictsort()
```
It does virtually the same as `.items()`

**Comment by hwhesselink** [comment]
I just submitted a PR to remove Wheezy from testing.

Agreed, using dictsort is a cleaner solution, I've updated the PR.

**Comment by myii** [comment]
Haven't checked this PR in any detail but please be aware of the various issues surrounding `|dictsort` and `.items()` here:

* https://github.com/saltstack-formulas/bind-formula/issues/146

**Comment by hwhesselink** [comment]
Hi @myii, the `|dictsort` change only applies to the zone and interface names.  They are always strings, and the sort order doesn't matter (the previous `iteritems` and `items` also don't sort), so I don't think there are issues in this case.  I've been using the code in production for a while.

Thanks for merging the "Drop wheezy testing" PR. Travis is still failing with that test atm, do I need to do anything to this PR to update the testing?

**Comment by myii** [comment]
> Hi @myii, the `|dictsort` change only applies to the zone and interface names. They are always strings, and the sort order doesn't matter (the previous `iteritems` and `items` also don't sort), so I don't think there are issues in this case. I've been using the code in production for a while.

@hwhesselink That should be absolutely fine, then.  I'll just let @vutny confirm and merge this.

> Thanks for merging the "Drop wheezy testing" PR. Travis is still failing with that test atm, do I need to do anything to this PR to update the testing?

You're welcome.  There are two ways that we could proceed:

1. Usually, the contributor can rebase on the latest merged changes and then force push the PR's branch again -- that would avoid the `wheezy` failure here.
1. However, since we've already merged that and the other jobs are passing, we can just go ahead and merge this as-is -- they'll pass in the merge commit.

Essentially, don't worry about it in this particular PR but you may need to use option 1 elsewhere.

**Comment by myii** [comment]
> ... (the previous `iteritems` and `items` also don't sort)

Just a note, as mentioned [here](https://github.com/saltstack-formulas/bind-formula/issues/146#issuecomment-609012016), `.items()` isn't random anymore since around Python 3.6.

**Comment by hwhesselink** [comment]
@myii, great, I'll wait for the merge.

My original PR actually used `.items()` but I changed it to use `|dictsort` based on @vutny's comment earlier in this thread.  Both work fine.

After this is merged I'll submit a larger patch to update the formula to work with Shorewall v5.

**Comment by myii** [comment]
Any final comments, @vutny?  Would you mind merging if this is ready to go?

**Review by vutny — APPROVED** [review]
All is fine, thanks for keeping me in the loop! :smiley:

**Comment by myii** [comment]
Merged, thanks for the PR @hwhesselink and for the review @vutny.

**Pull request merged**
